apiVersion: apps/v1
kind: Deployment 
metadata:
  name: car-serv-deployment
  namespace: car-serv
spec:
  selector:
    matchLabels:
      app: car-serv
  replicas: 1
  template:
    metadata:
      labels:
        app: car-serv
    spec:
      containers:
        - name: car-serv
          image: elroydevops/car-serv 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: car-serv-service
  namespace: car-serv
spec:
  type: ClusterIP 
  selector:
    app: car-serv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: car-serv-ingress
  namespace: car-serv
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: car-serv-cloud.devopsedu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: car-serv-service
                port:
                  number: 80