version: '3.8'

services:
  rancher:
    image: rancher/rancher:v2.11.2
    container_name: rancher-server
    restart: unless-stopped
    ports:
      - '80:80' # HTTP UI
      - '1503:443' # HTTPS UI
    volumes:
      - rancher-data:/var/lib/rancher
    environment:
      - CATTLE_BOOTSTRAP_PASSWORD=admin
    privileged: true

volumes:
  rancher-data:
